### ISSUE TITLE
Bagian dashboard kedua

### ISSUE THREAD

**Issue by aldiskatel** [faiz9877/web.github.io#22]
Ini didalam **admin/dashboard.php**
gasan menampilkan jumlah user yang terdaftar, mohon dibantu penyelesaiannya apakah itu close mysql atau langsung reset @faiz9877 @ikydhana .
```
    include_once('../koneksi.php');
    $wkwk1=mysqli_query($koneksi, "SELECT COUNT(id) AS total1 FROM users");
    $val=mysqli_fetch_assoc($wkwk1);
    $sql_hitung=$val['total1'];
    mysqli_close($koneksi);
    $wkwk2=mysqli_query($koneksi, "SELECT COUNT(nik) AS total2 FROM karyawan");
    $val=mysqli_fetch_assoc($wkwk2);
    $sql_hitung2=$val['total2'];
    mysqli_close($koneksi);
```

**Comment by faiz9877** [comment]
mohon suhu penjelasn apa itu "close mysql" & "($wkwk2)" pada line 7 ,8

**Comment by aldiskatel** [comment]
nah itu aku bingung, amun di java setiap open mysql itu harus diclose, apakah di php kaya itu jua cuman di aku kd mau itu. kayapa biar  query sql itu teubah

**Comment by faiz9877** [comment]
https://stackoverflow.com/

**Comment by aldiskatel** [comment]
apa yg new iz

**Comment by faiz9877** [comment]
blm ada lh

**Comment by faiz9877** [comment]
![image](https://user-images.githubusercontent.com/33045014/56673080-363f2880-66ea-11e9-864f-6a2a49bc6ef7.png)

**Comment by faiz9877** [comment]
jir kwa ngirim foto jua

**Comment by aldiskatel** [comment]
itu setelah kah sebelum?

**Comment by faiz9877** [comment]
setelah kurubah nama tabel nya jdi users

**Comment by faiz9877** [comment]
![image](https://user-images.githubusercontent.com/33045014/56673719-5de2c080-66eb-11e9-9f70-2864d1494872.png)

**Comment by faiz9877** [comment]
untuk koneksi yg didalam folder admin tu kyp d  ganti kh atau biar aja

**Comment by aldiskatel** [comment]
wih harat leh,
maksud $halaman diarahkan ke apa aja?

**Comment by aldiskatel** [comment]
iz amun isset itu biasakan pake if dimukanya atau try catch, soalnya amun getternya kosong kacau

**Comment by faiz9877** [comment]
d arahkan ny ke users

**Comment by aldiskatel** [comment]
ulah pull pang dikomentar tulis

**Comment by faiz9877** [comment]
![image](https://user-images.githubusercontent.com/33045014/56674617-f0d02a80-66ec-11e9-9cc2-310c83f40aac.png)

**Comment by aldiskatel** [comment]
itu yang ku ulah kah?

**Comment by faiz9877** [comment]
mau ai dah timbul table ny
tetinggal if (!$link)  d koneksi nya

**Comment by aldiskatel** [comment]
oke, yang bagian atas tadi maukah sudah jua
nang ini
https://github.com/faiz9877/web.github.io/issues/22#issuecomment-486299715

**Comment by faiz9877** [comment]
mau2 dh

**Comment by aldiskatel** [comment]
oke coba pull
